# Generated by Django 2.0.6 on 2018-07-29 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='pictures/')),
                ('status', model_utils.fields.StatusField(choices=[('borrowed', 'borrowed'), ('available', 'available')], default='borrowed', max_length=100, no_check_for_status=True)),
                ('borrowed_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'available'})),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 7, 29, 5, 22, 10, 171851, tzinfo=utc))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Book')),
            ],
        ),
    ]
