# Generated by Django 2.0.6 on 2018-07-29 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20180729_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 9, 8, 2, 620811, tzinfo=utc)),
        ),
    ]
