# Generated by Django 2.0.6 on 2018-07-29 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20180729_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 9, 9, 4, 254679, tzinfo=utc)),
        ),
    ]
