# Generated by Django 2.0.6 on 2018-08-01 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20180729_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 12, 16, 53, 655355, tzinfo=utc)),
        ),
    ]
