# Generated by Django 2.0.6 on 2018-08-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20180801_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='title',
        ),
    ]
